services:
  wp_db:
    container_name: wp_db
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
    - wp_network

  wp:
    container_name: wp
    build: ../dockerfiles/wordpress
    image: wordpress_local:1.0
    depends_on:
      - wp_db
    volumes:
      - ./wordpress:/var/www/html
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wp_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
    - wp_network
    
networks:
  wp_network:
    driver: bridge